In [1]:
import os
import pickle as pkl

import numpy as np
import pandas as pd

def load_pkl(file_path) :
    
    with open(file_path, 'rb') as f:
        
        df = pkl.load(f)
        
    return df

from transformers import BertTokenizerFast

# tokenizer_for_load = BertTokenizerFast.from_pretrained('./model/BertTokenizer-6000-32000-vocab.txt'
#                                                    , strip_accents=False
#                                                    , lowercase=False)
def save_pkl(df, file_path) :
    
    with open(file_path, 'wb') as f:
        pkl.dump(df, f)

In [2]:
import tensorflow as tf

In [12]:
dataset = tf.data.TFRecordDataset('./Q_Bert00.tfrecords')

In [24]:

tokenizer_for_load = BertTokenizerFast.from_pretrained('./model/BertTokenizer-3000-32000-vocab.txt'
                                                   , strip_accents=False
                                                   , lowercase=False)

Calling BertTokenizerFast.from_pretrained() with the path to a single file or url is deprecated


In [13]:
def _parse_function(example_proto):
  # Parse the input `tf.train.Example` proto using the dictionary above.
  return tf.io.parse_single_example(example_proto, feature_description)

def _select_data_from_record(record):
    """Filter out features to use for pretraining."""
    x = {
        'input_ids': record['input_ids'],
        'input_mask': record['input_mask'],
        'segment_ids': record['segment_ids'],
        'masked_lm_positions': record['masked_lm_positions'],
        'masked_lm_ids': record['masked_lm_ids'],
        'masked_lm_weights': record['masked_lm_weights'],
    }
    if use_next_sentence_label:
        x['next_sentence_labels'] = record['next_sentence_labels']
    if use_position_id:
        x['position_ids'] = record['position_ids']

    # TODO(hongkuny): Remove the fake labels after migrating bert pretraining.
    if output_fake_labels:
        return (x, record['masked_lm_weights'])
    else:
        return x


In [14]:
use_next_sentence_label = True
output_fake_labels = True
use_position_id = False

In [15]:
feature_description = {
    'input_ids': tf.io.FixedLenFeature([256], tf.int64),
    'segment_ids': tf.io.FixedLenFeature([256], tf.int64),
    'input_mask': tf.io.FixedLenFeature([256], tf.int64),
    'masked_lm_positions': tf.io.FixedLenFeature([40], tf.int64),
    'masked_lm_ids': tf.io.FixedLenFeature([40], tf.int64),
    'masked_lm_weights': tf.io.FixedLenFeature([40], tf.float32),
    'next_sentence_labels': tf.io.FixedLenFeature([1], tf.int64),
}


In [25]:
dataset = dataset.map(_parse_function,
                                   num_parallel_calls=tf.data.experimental.AUTOTUNE) # String to Example
dataset = dataset.map(_select_data_from_record,
                                                num_parallel_calls=tf.data.experimental.AUTOTUNE) # Example to InputData

TypeError: in user code:


    TypeError: tf___parse_function() takes 1 positional argument but 2 were given


In [17]:
a = next(iter(dataset))

In [20]:
a[0]['input_ids']

<tf.Tensor: shape=(256,), dtype=int64, numpy=
array([    2,  8590,  1811,  2422,  3049, 12659,    12,    15, 11106,
        5756,  6086,    61,    13,   544,     4,     4, 26570,  8144,
        3183,  5907,    12,  8842,    61,  8210,    13,  6171,    17,
        6005,    17,     4,  6064,    17, 21318,  2422,  9547, 10830,
        3132,  1501,     4,  8888,    40,  3105,  3090, 17928,  6630,
           4,     3,  8638,     4,  3129,  6172, 16354,    17,     3,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,   

In [26]:
word_df = pd.DataFrame({ "학습데이터" : tokenizer_for_load.convert_ids_to_tokens(a[0]['input_ids']),
                         "세그먼트_EMB" : a[0]['segment_ids']})


In [29]:
a[0].keys()

dict_keys(['input_ids', 'input_mask', 'segment_ids', 'masked_lm_positions', 'masked_lm_ids', 'masked_lm_weights', 'next_sentence_labels'])

In [34]:
ind

29

In [35]:
a[0]['masked_lm_positions']

<tf.Tensor: shape=(40,), dtype=int64, numpy=
array([29, 40, 45, 38, 48, 14, 16, 15,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0], dtype=int64)>

In [37]:
a[0]['masked_lm_ids']

<tf.Tensor: shape=(40,), dtype=int64, numpy=
array([ 6657, 13425,    17,  3049, 11660,  9288,  5649,  6008,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0], dtype=int64)>

In [36]:
a[0]['masked_lm_positions']

<tf.Tensor: shape=(40,), dtype=int64, numpy=
array([29, 40, 45, 38, 48, 14, 16, 15,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0], dtype=int64)>

In [39]:
i, ind

(0, 29)

In [41]:
a[0]['masked_lm_ids'][0]

<tf.Tensor: shape=(), dtype=int64, numpy=6657>

In [45]:
a[0]['masked_lm_ids'][i].numpy()

6657

In [49]:
for i, ind in enumerate(a[0]['masked_lm_positions']) :
    ind = ind.numpy()
    word_df.loc[ind, "MASKED_LABEL"] = tokenizer_for_load.convert_ids_to_tokens([a[0]['masked_lm_ids'][i].numpy()])
    word_df.loc[ind, "MASKED_WEIGHT"] = a[0]['masked_lm_weights'][i].numpy()

In [52]:
a[0]

{'input_ids': <tf.Tensor: shape=(256,), dtype=int64, numpy=
 array([    2,  8590,  1811,  2422,  3049, 12659,    12,    15, 11106,
         5756,  6086,    61,    13,   544,     4,     4, 26570,  8144,
         3183,  5907,    12,  8842,    61,  8210,    13,  6171,    17,
         6005,    17,     4,  6064,    17, 21318,  2422,  9547, 10830,
         3132,  1501,     4,  8888,    40,  3105,  3090, 17928,  6630,
            4,     3,  8638,     4,  3129,  6172, 16354,    17,     3,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,   

In [50]:
word_df.head(50)

학습데이터  세그먼트_EMB MASKED_LABEL  MASKED_WEIGHT
0    [CLS]         0        [PAD]            0.0
1      제임스         0          NaN            NaN
2        얼         0          NaN            NaN
3        카         0          NaN            NaN
4      ##터         0          NaN            NaN
5      주니어         0          NaN            NaN
6        (         0          NaN            NaN
7        ,         0          NaN            NaN
8    1924년         0          NaN            NaN
9      10월         0          NaN            NaN
10      1일         0          NaN            NaN
11       ~         0          NaN            NaN
12       )         0          NaN            NaN
13       는         0          NaN            NaN
14  [MASK]         0          민주당            1.0
15  [MASK]         0           출신            1.0
16     번역한         0           미국            1.0
17      39         0          NaN            NaN
18     ##대         0          NaN            NaN
19     대통령         0          NaN            NaN
20       (         0          NaN            NaN
21   1977년         0          NaN            NaN
22       ~         0          NaN            NaN
23   1981년         0          NaN            NaN
24       )         0          NaN            NaN
25      이다         0          NaN            NaN
26       .         0          NaN            NaN
27      생애         0          NaN            NaN
28       .         0          NaN            NaN
29  [MASK]         0           어린            1.0
30      시절         0          NaN            NaN
31       .         0          NaN            NaN
32      지미         0          NaN            NaN
33       카         0          NaN            NaN
34    ##터는         0          NaN            NaN
35     조지아         0          NaN            NaN
36     ##주         0          NaN            NaN
37       섬         0          NaN            NaN
38  [MASK]         0          ##터            1.0
39     카운티         0          NaN            NaN
40       h         0           플레            1.0
41     ##인         0          NaN            NaN
42     ##스         0          NaN            NaN
43    마을에서         0          NaN            NaN
44    태어났다         0          NaN            NaN
45  [MASK]         0            .            1.0
46   [SEP]         0          NaN            NaN
47    아카데미         1          NaN            NaN
48  [MASK]         1           각본            1.0
49     ##상         1          NaN            NaN

In [47]:
df[idx]['NSP']

[0, 1]

In [51]:
word_df.tail(50)

학습데이터  세그먼트_EMB MASKED_LABEL  MASKED_WEIGHT
206  [PAD]         0          NaN            NaN
207  [PAD]         0          NaN            NaN
208  [PAD]         0          NaN            NaN
209  [PAD]         0          NaN            NaN
210  [PAD]         0          NaN            NaN
211  [PAD]         0          NaN            NaN
212  [PAD]         0          NaN            NaN
213  [PAD]         0          NaN            NaN
214  [PAD]         0          NaN            NaN
215  [PAD]         0          NaN            NaN
216  [PAD]         0          NaN            NaN
217  [PAD]         0          NaN            NaN
218  [PAD]         0          NaN            NaN
219  [PAD]         0          NaN            NaN
220  [PAD]         0          NaN            NaN
221  [PAD]         0          NaN            NaN
222  [PAD]         0          NaN            NaN
223  [PAD]         0          NaN            NaN
224  [PAD]         0          NaN            NaN
225  [PAD]         0          NaN            NaN
226  [PAD]         0          NaN            NaN
227  [PAD]         0          NaN            NaN
228  [PAD]         0          NaN            NaN
229  [PAD]         0          NaN            NaN
230  [PAD]         0          NaN            NaN
231  [PAD]         0          NaN            NaN
232  [PAD]         0          NaN            NaN
233  [PAD]         0          NaN            NaN
234  [PAD]         0          NaN            NaN
235  [PAD]         0          NaN            NaN
236  [PAD]         0          NaN            NaN
237  [PAD]         0          NaN            NaN
238  [PAD]         0          NaN            NaN
239  [PAD]         0          NaN            NaN
240  [PAD]         0          NaN            NaN
241  [PAD]         0          NaN            NaN
242  [PAD]         0          NaN            NaN
243  [PAD]         0          NaN            NaN
244  [PAD]         0          NaN            NaN
245  [PAD]         0          NaN            NaN
246  [PAD]         0          NaN            NaN
247  [PAD]         0          NaN            NaN
248  [PAD]         0          NaN            NaN
249  [PAD]         0          NaN            NaN
250  [PAD]         0          NaN            NaN
251  [PAD]         0          NaN            NaN
252  [PAD]         0          NaN            NaN
253  [PAD]         0          NaN            NaN
254  [PAD]         0          NaN            NaN
255  [PAD]         0          NaN            NaN

In [50]:
word_df.tail(50)

학습데이터    라벨링  세그먼트_EMB  MASK
27   [SEP]  [SEP]         0   0.0
28       버      버         1   0.0
29    ##기는   ##기는         1   0.0
30       몇      몇         1   0.0
31     ##억    ##억         1   0.0
32    ##베리   ##베리         1   0.0
33     ##나    ##나         1   0.0
34      하는     하는         1   0.0
35      악마     악마         1   0.0
36     ##의    ##의         1   0.0
37      열매     열매         1   0.0
38     ##를    ##를         1   0.0
39       팔      팔         1   0.0
40     ##고    ##고         1   0.0
41       ,      ,         1   0.0
42      보물     보물         1   0.0
43    ##지도   ##지도         1   0.0
44     ##로    ##로         1   0.0
45      보물     보물         1   0.0
46     ##을    ##을         1   0.0
47       찾      찾         1   0.0
48    ##으려   ##으려         1   0.0
49     했지만    했지만         1   0.0
50       ,      ,         1   0.0
51     갑자기    갑자기         1   0.0
52     나타난    나타난         1   0.0
53       샹      샹         1   0.0
54  [MASK]   ##크스         1   1.0
55     ##로    ##로         1   0.0
56      인해     인해         1   0.0
57       깜      깜         1   0.0
58     ##짝    ##짝         1   0.0
59      놀라     놀라         1   0.0
60      악마     악마         1   0.0
61     ##의    ##의         1   0.0
62      열매     열매         1   0.0
63     ##를    ##를         1   0.0
64       삼      삼         1   0.0
65     ##켜    ##켜         1   0.0
66  [MASK]   ##버리         1   1.0
67     ##고    ##고         1   0.0
68  [MASK]     보물         1   1.0
69    ##지도   ##지도         1   0.0
70     ##를    ##를         1   0.0
71     바다에    바다에         1   0.0
72     떨어뜨    떨어뜨         1   0.0
73     ##려    ##려         1   0.0
74     버렸다    버렸다         1   0.0
75       .      .         1   0.0
76   [SEP]  [SEP]         1   0.0

In [7]:
splited_len

13408

In [9]:
split_ = 20

In [10]:
input_files = ['./dt/wiki_ko_dict1_p.pkl', './dt/wiki_ko_dict2_p.pkl']

i = 1

for input_file in input_files :
    
    pk = load_pkl(input_file)
    keys = list(pk.keys())
    
    splited_len = len(keys) // split_
    

    for ind in range(split_) :
        
        tmp_dict = {}
        if ind == split_ - 1 :
            target_key = keys[ind*splited_len :]
        else :
            target_key = keys[ind * splited_len : (ind+1) *splited_len]
        
        for key in target_key :

            tmp_dict[key] = pk[key]
            
        save_pkl(tmp_dict, './dt/wiki_ko_dict-{}.pkl'.format(str(i).zfill(2)))
        i+=1
